replicaCount: 1

image:
  repository: ""   # e.g. us-central1-docker.pkg.dev/PROJECT/payment-api-repo/payment-api
  tag: ""          # set by pipeline (github.sha)
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "payment-api"

serviceAccount:
  create: true
  name: "payment-api"
  annotations: {}
    # iam.gke.io/gcp-service-account: payment-api-sa@PROJECT.iam.gserviceaccount.com

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  staticIpName: "payment-api-ingress-ip"  # matches google_compute_global_address in Terraform

env: []
  # - name: GCP_PROJECT_ID
  #   value: "your-project-id"
  # - name: SECRET_NAME
  #   value: "payment-api-key"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
