# Staging environment overrides
replicaCount: 2

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: payment-api-sa@YOUR_PROJECT_ID.iam.gserviceaccount.com

env:
  - name: GCP_PROJECT_ID
    value: "YOUR_PROJECT_ID"
  - name: SECRET_NAME
    value: "payment-api-key"
